### ISSUE TITLE
Unstable readings on the SHT85 sensor

### ISSUE THREAD

**Issue by wavewolf** [Sensirion/arduino-sht#13] opened 2020-06-23 16:44 UTC
I can't get stable readings on the SHT85 sensor. 
I use the example code "sht-autodetect" and this is what is printed by the serial monitor:

<img width="321" alt="Captura" src="https://user-images.githubusercontent.com/22566382/85431061-4ae2af00-b581-11ea-841d-d568df056b50.PNG">

And sometimes it doesn't even give me readings, it just gives me "Error in readSample()".
What could be going on?

**Comment by winkj** [comment] 2020-06-23 16:48
Which Arduino board are you using for this test? And are there any other sensors connected to the I2C bus?

**Comment by wavewolf** [comment] 2020-06-23 16:52
I forgot to say, I'm sorry, I'm using the ESP32 development board.
It may not be entirely compatible?

**Comment by winkj** [comment] 2020-06-23 17:29
I've previously tested on ESP32 - an Adafruit HUZZAH32 - and didn't experience issues, but will do more testing.

Since you had issues on and off, one possibility could be a connection issue. Is this using a third party sensor board, or is it a direct connection with soldered wires?

**Comment by wavewolf** [comment] 2020-06-23 19:38
I have sensirion SHT85 module wired to the ESP32 module.
 If you say that it works correctly in your tests, I can think that it is a problem with my cables or that the sensor is defective.

**Comment by wavewolf** [comment] 2020-06-24 12:14
I have news, I have continued to do tests and it works fine if I restart the module a couple of times. The first two times, it usually gives me that error, but the third time, it manages to start and print the values. I'm still investigating.

**Comment by erickkill** [comment] 2020-11-23 03:50
Hi,

How wiring the sensor on ESP32 pins?

What the sequence?

**Comment by TechnicalLee** [comment] 2021-02-03 22:27
Try what the author of #10 suggested as a fix, that solved all the sensor errors for me as well.

**Comment by winkj** [comment] 2021-03-08 19:09
Closing for now; if this is a reproducible issue, please feel free to reopen

**Closed as completed by winkj** 2021-03-08 19:09 UTC
